-- MySQL Script generated by MySQL Workbench
-- Tue Nov 22 11:50:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema game
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema game
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `game` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `game` ;

-- -----------------------------------------------------
-- Table `game`.`partida_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`partida_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_partida` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `game`.`partidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`partidas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dado1` INT NOT NULL,
  `dado2` INT NOT NULL,
  `resultado` VARCHAR(255) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `game`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `game`.`usuarios_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`usuarios_roles` (
  `usuario_id` INT NOT NULL,
  `rol_id` INT NOT NULL,
  INDEX `FK6yxg1lhuv5nievqea7rvn6afm` (`rol_id` ASC) VISIBLE,
  INDEX `FKdki9m2shsixtcdefujrsqyq0f` (`usuario_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `game`.`usuaris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`usuaris` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `partida_id` TINYBLOB NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `ranquing` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

